//
//  DeveloperPreview.swift
//  AirBnb
//
//  Created by Shravak Jain on 26/10/24.
//

import Foundation
class DeveloperPreview{
    static let shared = DeveloperPreview()
    var listing : [Listing] = [
        .init(
             id: NSUUID().uuidString,
             ownerUid: NSUUID().uuidString,
             ownerName: "Shravak Jain",
             ownerImageUrls:"male-profile-photo",
             numberOfBeds: 4,
             numberOfBathrooms: 3,
             numberOfGuests: 4,
             numberOfBedrooms: 4,
             priceForNight : 567,
             latitude : 28.7850,
             Longitude :  -80.1936,
             imageUrls: ["listing5", "listing4", "listing1", "listing5", "listing3", "listing2"],
             address: "124 Main St",
             city: "Miami",
             state : "Florida",
             title : "Vidhya Vila",
             raiting : 4.85,
             features: [.selfCheckIn, .superHost],
             amenities : [.wifi, .alarmSystem, .balcony, .tv , .laundry],
             type: [.vila]
        ),
        .init(
            id : NSUUID().uuidString,
             ownerUid: NSUUID().uuidString,
             ownerName: "Samartha Jain",
             ownerImageUrls: "male-profile-photo",
             numberOfBeds: 4,
             numberOfBathrooms: 3,
             numberOfGuests: 4,
             numberOfBedrooms: 4,
             priceForNight : 567,
             latitude : 28.7850,
             Longitude :  -80.1936,
             imageUrls: ["listing4", "listing2", "listing5", "listing3", "listing1", "listing6"],
             address: "124 Main St",
             city: "Indore",
             state : "Madhya Pradesh",
             title : "Samartha Vila",
             raiting : 4.85,
             features: [.selfCheckIn, .superHost],
             amenities : [.wifi, .alarmSystem, .balcony, .tv , .laundry],
            type: [.vila]
        ),
        .init(
            id : NSUUID().uuidString,
             ownerUid: NSUUID().uuidString,
             ownerName: "Namo Jain",
             ownerImageUrls: "male-profile-photo",
             numberOfBeds: 4,
             numberOfBathrooms: 3,
             numberOfGuests: 4,
             numberOfBedrooms: 4,
             priceForNight : 867,
             latitude : 28.7850,
             Longitude :  -80.1936,
             imageUrls: ["listing2", "listing3", "listing1", "listing5", "listing4"],
             address: "124 Main St",
             city: "Mumbai",
             state : "Maharashtra",
             title : "Namo Vila",
             raiting : 4.25,
             features: [.selfCheckIn, .superHost],
             amenities : [.wifi, .alarmSystem, .balcony, .tv , .laundry],
            type: [.house]
        ),
        .init(
            id : NSUUID().uuidString,
             ownerUid: NSUUID().uuidString,
             ownerName: "Shravak Jain",
             ownerImageUrls: "male-profile-photo",
             numberOfBeds: 4,
             numberOfBathrooms: 3,
             numberOfGuests: 4,
             numberOfBedrooms: 4,
             priceForNight : 967,
             latitude : 25.7850,
             Longitude :  -80.1936,
             imageUrls: ["listing1", "listing5", "listing6", "listing2", "listing4","listing3"],
             address: "124 Main St",
             city: "Indore",
             state : "Rajasthan",
             title : "Shravak Vila",
             raiting : 4.35,
             features: [.selfCheckIn, .superHost],
             amenities : [.wifi, .alarmSystem, .balcony, .tv , .laundry],
            type: [.apartment]
        ),
        .init(
            id : NSUUID().uuidString,
             ownerUid: NSUUID().uuidString,
             ownerName: "Shailendra Jain",
             ownerImageUrls: "male-profile-photo",
             numberOfBeds: 4,
             numberOfBathrooms: 3,
             numberOfGuests: 4,
             numberOfBedrooms: 4,
             priceForNight : 567,
             latitude : 28.7850,
             Longitude :  -80.1936,
             imageUrls: ["listing3", "listing2", "listing5", "listing4", "listing1", "listing6"],
             address: "124 Main St",
             city: "Indore",
             state : "Madhya Pradesh",
             title : "Shailendra Vila",
             raiting : 4.85,
             features: [.selfCheckIn, .superHost],
             amenities : [.wifi, .alarmSystem, .balcony, .tv , .laundry],
            type: [.vila]
        ),
        .init(
            id : NSUUID().uuidString,
             ownerUid: NSUUID().uuidString,
             ownerName: "Shraddha Jain",
             ownerImageUrls: "male-profile-photo",
             numberOfBeds: 4,
             numberOfBathrooms: 3,
             numberOfGuests: 4,
             numberOfBedrooms: 4,
             priceForNight : 567,
             latitude : 28.7850,
             Longitude :  -80.1936,
             imageUrls: ["listing6", "listing2", "listing5", "listing4", "listing1", "listing6"],
             address: "124 Main St",
             city: "Indore",
             state : "Madhya Pradesh",
             title : "Shraddha Vila",
             raiting : 4.85,
             features: [.selfCheckIn, .superHost],
             amenities : [.wifi, .alarmSystem, .balcony, .tv , .laundry],
            type: [.vila]
        )
        
    ]
}
